apiVersion: v1
kind: Pod
metadata:
  name: heavy-api
  namespace: dev
  labels:
    app: heavy-api
spec:
  containers:
    - name: heavy-api
      image: marychandana484742/color-api:1.1.0
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "1" # 1 full CPU
          memory: "1Gi" # 1 Gigabyte
        limits:
          cpu: "2" # 2 CPUs
          memory: "2Gi" # 2 Gigabytes
