apiVersion: v1
kind: Pod
metadata:
  name: curl2
  labels:
    app: curl2
    tier: backend
spec:
  containers:
    - name: curl2
      image: lmacademy/alpine-curl:1.0.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
