# Equivalent to the imperative command:
# kubectl expose pod nginx-pod --type=NodePort --port=80

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80 # Service port (clients use this to access the app)
      targetPort: 80 # Pod port (where nginx is actually listening)
      protocol: TCP
