apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  labels:
    name: color-api-pod
spec:
  containers:
    - name: color-api-pod
      image: marychandana484742/color-api:1.2.0
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
      env:
        - name: DELAY_STARTUP
          value: "false"
      startupProbe:
        httpGet:
          path: /health
          port: 80
        failureThreshold: 2
        periodSeconds: 3
