apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
nameSuffix: -alpha

commonLabels:
  project: ecommerce-app
  tier: backend
  env: dev

commonAnnotations:
  team: finance
  maintainer: "finance@ourcompany.org"
  repository: "git-repo"

replicas:
  - name: nginx
    count: 2
