apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
    - name: traffic-generator
      image: marychandana484742/traffic-generator:1.0.0
      args:
        - "color-api-svc/api"
        - "0.5"
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
