apiVersion: v1
kind: Pod
metadata:
  name: pink-color-api
  labels:
    app: pink-color-api
spec:
  containers:
    - name: color-api
      image: marychandana484742/color-api:1.3.0
      envFrom:
        - configMapRef:
            name: pink-env-vars
      volumeMounts:
        - name: color-config
          mountPath: /mnt/config
          readOnly: true
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  volumes:
    - name: color-config
      configMap:
        name: pink-files
