apiVersion: v1
kind: Pod
metadata:
  name: color-api
  namespace: dev
  labels:
    app: color-api
spec:
  containers:
    - name: color-api
      image: marychandana484742/color-api:1.1.0
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: color-api-svc
  namespace: dev
  labels:
    app: color-api
spec:
  type: ClusterIP
  selector:
    app: color-api
  ports:
    - port: 80
      targetPort: 80
