apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: pod-reader
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: bob
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: pod-inspector
    namespace: dev
