apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.36.1
      command:
        - "sh"
        - "-c"
        - "sleep 1800"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: db-secrets
          mountPath: /etc/db
  volumes:
    - name: db-secrets
      secret:
        secretName: db-creds
        items:
          - key: password
            path: dev/password
