apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.36.1
      command:
        - "sh"
        - "-c"
        - 'echo "$username" && echo "$password" && sleep 1800'
      envFrom:
        - secretRef:
            name: db-creds
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
